drop table CDProjectNumbers;
create table CDProjectNumbers (ProjectNumber int,	ProjectName varchar(75));

insert into CDProjectNumbers values (14362,'Matrix NRE Busware') ;
insert into CDProjectNumbers values (14363,'Matrix NRE AVM') ;
insert into CDProjectNumbers values (14364,'Matrix NRE Bustime') ;
insert into CDProjectNumbers values (14365,'Matrix NRE BLFM') ;
insert into CDProjectNumbers values (14366,'Matrix NRE CleverCAD') ;
insert into CDProjectNumbers values (14367,'Matrix NRE CleverAnalytics') ;
insert into CDProjectNumbers values (14368,'Matrix NRE Clever Reports') ;
insert into CDProjectNumbers values (14369,'Matrix NRE CleverWorks') ;
insert into CDProjectNumbers values (14370,'Matrix NRE FeatureTeam') ;
insert into CDProjectNumbers values (14371,'Matrix NRE SmartYard') ;
insert into CDProjectNumbers values (14372,'Matrix NRE Infotainment') ;
insert into CDProjectNumbers values (14373,'Matrix NRE GreyHawk') ;
insert into CDProjectNumbers values (15160,'Matrix NRE RCP') ;
insert into CDProjectNumbers values (15060,'Matrix NRE CleverWare') ;
insert into CDProjectNumbers values (10790,'Bustime Agile') ;
insert into CDProjectNumbers values (11690,'Busware') ;
insert into CDProjectNumbers values (11091,'CCADA') ;
insert into CDProjectNumbers values (10693,'NRE') ;
insert into CDProjectNumbers values (10390,'Cleverworks') ;
insert into CDProjectNumbers values (10180,'Greyhawk') ;
insert into CDProjectNumbers values (10590,'SmartYard') ;
insert into CDProjectNumbers values (10200,'CRS') ;
insert into CDProjectNumbers values (10291,'AVMA') ;
insert into CDProjectNumbers values (10692,'ACE') ;
insert into CDProjectNumbers values (12191,'CleverWare') ;
insert into CDProjectNumbers values (10027,'DCC') ;
